version: "3.9"

services:

  postgis:
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend

  api:
    build: ./backend
    container_name: donation_api
    depends_on:
      postgis:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "8080:8080"

    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
